#!/usr/bin/with-contenv bash
# shellcheck shell=bash

conf_path=/aria2/conf
conf_copy_path=/aria2/conf-copy
data_path=/aria2/data

# If config does not exist - use default
if [ ! -f $conf_path/aria2.conf ]; then
    cp $conf_copy_path/aria2.conf $conf_path/aria2.conf
    sed -i '/^bt-tracker=/d' $conf_path/aria2.conf
    # printf 'bt-tracker=%s\n' "${TRACKERS}" >>$conf_path/aria2.conf
fi

if [ -n "$RPC_SECRET" ]; then
    sed -i '/^rpc-secret=/d' $conf_path/aria2.conf
    printf 'rpc-secret=%s\n' "${RPC_SECRET}" >>$conf_path/aria2.conf
fi

touch $conf_path/aria2.session



# userid="$(id -u)" # 65534 - nobody, 0 - root
# groupid="$(id -g)"

# if [[ -n "$PUID" && -n "$PGID" ]]; then
#     userid=$PUID
#     groupid=$PGID
# fi

chown -R "$PUID":"$PGID" $conf_path
chown -R "$PUID":"$PGID" $data_path